# Generated by Django 6.0.1 on 2026-02-11 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='joined_date',
            new_name='task_time',
        ),
    ]
