# Generated by Django 6.0.1 on 2026-02-11 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_app', '0002_rename_joined_date_member_task_time'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='To_do_task',
        ),
    ]
