# Generated by Django 6.0.1 on 2026-02-11 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_app', '0003_rename_member_to_do_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deleted_task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_task', models.CharField(max_length=255)),
                ('task_time', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
