# Generated by Django 6.0.1 on 2026-02-11 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_app', '0004_deleted_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='compleated_task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_time', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
